apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
# These are the files Kustomize will process and Flux will apply
resources:
  # - ./ray/
  - helmreleases/raycluster.yaml

configMapGenerator:
- name: raycluster-values
  files:
    - values.yaml=configs/raycluster-values.yaml
  options:
    disableNameSuffixHash: true  # Keep name stable
