apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# These are the files Kustomize will process and Flux will apply
resources:
  # - ./ray/
  - helmreleases/raycluster.yaml
  - configs/raycluster-values.yaml
